mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="600"
mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="700"
mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="800"
mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="900"
mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="1000"

#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="200"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="250"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="300"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="350"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="400"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="450"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="500"


#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="170"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="200"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="300"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="400"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="500"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="600"

#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="5"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="10"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="20"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="30"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="40"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="50"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="60"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="70"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="80"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="90"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="100"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="110"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="120"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="130"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.SimpleQueryPerformanceTest  -Dexec.args="150"
##mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="5"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="10"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="20"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="30"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="40"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="50"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="60"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="70"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="80"
#mvn -q package exec:java -DskipTests -Dexec.mainClass=com.yugabyte.PrepareQueryPerformanceTest  -Dexec.args="100"
